services:
  php:
    build: .
    volumes:
      - .:/app
    working_dir: /app

  php-jit:
    build: .
    volumes:
      - .:/app
      - ./.docker/php-jit-igbinary.ini:/usr/local/etc/php/conf.d/kura.ini
    working_dir: /app
